### ISSUE TITLE
`--paper-chips-search-input` and `--paper-chips-search-input-placeholder` lost

### ISSUE THREAD

**Issue by ankon** [Collaborne/paper-chip#13]
d94f91eaa6cfb6f9e73724251d855c4327eddaef removed the ability to style the input with the `--paper-chips-search-input` style (without mentioning it), and 90ac1ac then removed the `--paper-chips-search-input-placeholder` and replaced it with separate variables. 

I suspect this is part of the implicit downsides of using lit-element, but we should somehow document this and provide some guidance as to how to continue styling the components.

(I guess this would be related to #12 - if one could style things more flexible, then there would be a workaround for that issue.)

**Comment by ronnyroeller** [comment]
Indeed, mixin’s are hard to use from LitElement. Also, the new material components seem to have also variable per value (instead of mixins).
Aside, the high flexibility of mixin’s have proven to be a poor idea. There is a high risk that the user of an element defines styling that conflicts with the elements current styling (or worse: with it’s current styling).

I’m closing this issue because the removal of the mixins is the expected and correct behavior.
